// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ParameterValidation.Strings.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Validation source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Validation.Recipes
{
    using System;
    using System.Collections;

    /// <summary>
    /// Contains all validations that can be applied to a <see cref="Parameter"/>.
    /// </summary>
#if !OBeautifulCodeValidationRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Validation", "See package version number")]
    internal
#else
    public
#endif
        static partial class ParameterValidation
    {
#pragma warning disable 1591
        public const string BeNullExceptionMessageSuffix = "is not null";

        public const string NotBeNullExceptionMessageSuffix = "is null";

        public const string BeTrueExceptionMessageSuffix = "is not true";

        public const string NotBeTrueExceptionMessageSuffix = "is true";

        public const string BeFalseExceptionMessageSuffix = "is not false";

        public const string NotBeFalseExceptionMessageSuffix = "is false";

        public const string NotBeNullNorWhiteSpaceExceptionMessageSuffix = "is white space";

        public const string BeEmptyGuidExceptionMessageSuffix = "is not an empty guid";

        public const string BeEmptyStringExceptionMessageSuffix = "is not an empty string";

        public const string BeEmptyEnumerableExceptionMessageSuffix = "is not an empty enumerable";

        public const string NotBeEmptyGuidExceptionMessageSuffix = "is an empty guid";

        public const string NotBeEmptyStringExceptionMessageSuffix = "is an empty string";

        public const string NotBeEmptyEnumerableExceptionMessageSuffix = "is an empty enumerable";

        public const string ContainSomeNullsExceptionMessageSuffix = "contains no null elements";

        public const string NotContainAnyNullsExceptionMessageSuffix = "contains at least one null element";

        public const string BeDefaultExceptionMessageSuffix = "is not equal to default(T), using EqualityComparer<T>.Default";

        public const string NotBeDefaultExceptionMessageSuffix = "is equal to default(T), using EqualityComparer<T>.Default";

        public const string BeLessThanExceptionMessageSuffix = "is not less than the comparison value, using Comparer<T>.Default";

#pragma warning restore 1591
    }
}