// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Verifications.Internal.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Assertion.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Assertion.Recipes
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Linq;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Contains all validations that can be applied to a <see cref="AssertionTracker"/>.
    /// </summary>
    [SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "A generalized parameter validation library is going to require lots of types.")]
#if !OBeautifulCodeAssertionRecipesProject
    internal
#else
    public
#endif
        static partial class Verifications
    {
        private static readonly HashSet<char> AlphaNumericCharactersHashSet =
            new HashSet<char>(
                new char[0]
                    .Concat(Enumerable.Range(48, 10).Select(Convert.ToChar))
                    .Concat(Enumerable.Range(65, 26).Select(Convert.ToChar))
                    .Concat(Enumerable.Range(97, 26).Select(Convert.ToChar)));

        private static readonly HashSet<char> AlphabeticCharactersHashSet =
            new HashSet<char>(
                new char[0]
                    .Concat(Enumerable.Range(65, 26).Select(Convert.ToChar))
                    .Concat(Enumerable.Range(97, 26).Select(Convert.ToChar)));

        private static void BeNullInternal(
            Verification verification)
        {
            if (!ReferenceEquals(verification.Value, null))
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeNullExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeNullInternal(
            Verification verification)
        {
            if (ReferenceEquals(verification.Value, null))
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeNullExceptionMessageSuffix);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentNullException(null, exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeTrueInternal(
            Verification verification)
        {
            var shouldThrow = ReferenceEquals(verification.Value, null) || ((bool)verification.Value != true);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeTrueExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeTrueInternal(
            Verification verification)
        {
            var shouldNotThrow = ReferenceEquals(verification.Value, null) || ((bool)verification.Value == false);
            if (!shouldNotThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeTrueExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeFalseInternal(
            Verification verification)
        {
            var shouldThrow = ReferenceEquals(verification.Value, null) || (bool)verification.Value;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeFalseExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeFalseInternal(
            Verification verification)
        {
            var shouldNotThrow = ReferenceEquals(verification.Value, null) || (bool)verification.Value;
            if (!shouldNotThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeFalseExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeNullNorWhiteSpaceInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var shouldThrow = string.IsNullOrWhiteSpace((string)verification.Value);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeNullNorWhiteSpaceExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeNullOrNotWhiteSpaceInternal(
            Verification verification)
        {
            var shouldThrow = !ReferenceEquals(verification.Value, null) && string.IsNullOrWhiteSpace((string)verification.Value);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeNullOrNotWhiteSpaceExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeEmptyGuidInternal(
            Verification verification)
        {
            var shouldThrow = ReferenceEquals(verification.Value, null) || ((Guid)verification.Value != Guid.Empty);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeEmptyGuidExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeEmptyGuidInternal(
            Verification verification)
        {
            var shouldThrow = (!ReferenceEquals(verification.Value, null)) && ((Guid)verification.Value == Guid.Empty);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeEmptyGuidExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1820:TestForEmptyStringsUsingStringLength", Justification = "string.IsNullOrEmpty does not work here")]
        private static void BeEmptyStringInternal(
            Verification verification)
        {
            var shouldThrow = (string)verification.Value != string.Empty;

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeEmptyStringExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1820:TestForEmptyStringsUsingStringLength", Justification = "string.IsNullOrEmpty does not work here")]
        private static void NotBeEmptyStringInternal(
            Verification verification)
        {
            var shouldThrow = (string)verification.Value == string.Empty;

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeEmptyStringExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "unused", Justification = "Cannot iterate without a local")]
        private static void BeEmptyEnumerableInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = false;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var unused in valueAsEnumerable)
            {
                shouldThrow = true;
                break;
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeEmptyEnumerableExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "unused", Justification = "Cannot iterate without a local")]
        private static void NotBeEmptyEnumerableInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = true;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var unused in valueAsEnumerable)
            {
                shouldThrow = false;
                break;
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeEmptyEnumerableExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "unused", Justification = "Cannot iterate without a local")]
        private static void BeEmptyDictionaryInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsDictionary = verification.Value as IDictionary;

            // ReSharper disable once PossibleNullReferenceException
            var shouldThrow = valueAsDictionary.Count != 0;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeEmptyDictionaryExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "unused", Justification = "Cannot iterate without a local")]
        private static void NotBeEmptyDictionaryInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsDictionary = verification.Value as IDictionary;

            // ReSharper disable once PossibleNullReferenceException
            var shouldThrow = valueAsDictionary.Count == 0;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeEmptyDictionaryExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void ContainSomeNullElementsInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = true;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var unused in valueAsEnumerable)
            {
                if (ReferenceEquals(unused, null))
                {
                    shouldThrow = false;
                    break;
                }
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, ContainSomeNullElementsExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotContainAnyNullElementsInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = false;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var unused in valueAsEnumerable)
            {
                if (ReferenceEquals(unused, null))
                {
                    shouldThrow = true;
                    break;
                }
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotContainAnyNullElementsExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void ContainSomeKeyValuePairsWithNullValueInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = true;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var keyValuePair in valueAsEnumerable)
            {
                if (ReferenceEquals(((dynamic)keyValuePair).Value, null))
                {
                    shouldThrow = false;
                    break;
                }
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, ContainSomeKeyValuePairsWithNullValueExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotContainAnyKeyValuePairsWithNullValueInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = verification.Value as IEnumerable;
            var shouldThrow = false;

            // ReSharper disable once PossibleNullReferenceException
            foreach (var keyValuePair in valueAsEnumerable)
            {
                if (ReferenceEquals(((dynamic)keyValuePair).Value, null))
                {
                    shouldThrow = true;
                    break;
                }
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotContainAnyKeyValuePairsWithNullValueExceptionMessageSuffix);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeDefaultInternal(
            Verification verification)
        {
            var defaultValue = GetDefaultValue(verification.ValueType);
            var shouldThrow = !EqualUsingDefaultEqualityComparer(verification.ValueType, verification.Value, defaultValue);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeDefaultExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeDefaultInternal(
            Verification verification)
        {
            var defaultValue = GetDefaultValue(verification.ValueType);
            var shouldThrow = EqualUsingDefaultEqualityComparer(verification.ValueType, verification.Value, defaultValue);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeDefaultExceptionMessageSuffix, Include.GenericType);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeLessThanInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) != CompareOutcome.Value1LessThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeLessThanExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeLessThanInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) == CompareOutcome.Value1LessThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeLessThanExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeGreaterThanInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) != CompareOutcome.Value1GreaterThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeGreaterThanExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeGreaterThanInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) == CompareOutcome.Value1GreaterThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeGreaterThanExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeLessThanOrEqualToInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) == CompareOutcome.Value1GreaterThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeLessThanOrEqualToExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeLessThanOrEqualToInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) != CompareOutcome.Value1GreaterThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeLessThanOrEqualToExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeGreaterThanOrEqualToInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) == CompareOutcome.Value1LessThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeGreaterThanOrEqualToExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeGreaterThanOrEqualToInternal(
            Verification verification)
        {
            var shouldThrow = CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) != CompareOutcome.Value1LessThanValue2;
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeGreaterThanOrEqualToExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeEqualToInternal(
            Verification verification)
        {
            var shouldThrow = !EqualUsingDefaultEqualityComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeEqualToExceptionMessageSuffix, Include.FailingValue | Include.GenericType);
                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeEqualToInternal(
            Verification verification)
        {
            var shouldThrow = EqualUsingDefaultEqualityComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value);
            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeEqualToExceptionMessageSuffix, Include.GenericType);
                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeInRangeInternal(
            Verification verification)
        {
            ThrowIfMalformedRange(verification.VerificationParameters);

            var shouldThrow = (CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) == CompareOutcome.Value1LessThanValue2) ||
                              (CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[1].Value) == CompareOutcome.Value1GreaterThanValue2);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeInRangeExceptionMessageSuffix, Include.FailingValue | Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void NotBeInRangeInternal(
            Verification verification)
        {
            ThrowIfMalformedRange(verification.VerificationParameters);

            var shouldThrow = (CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[0].Value) != CompareOutcome.Value1LessThanValue2) &&
                              (CompareUsingDefaultComparer(verification.ValueType, verification.Value, verification.VerificationParameters[1].Value) != CompareOutcome.Value1GreaterThanValue2);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeInRangeExceptionMessageSuffix, Include.GenericType);

                if (verification.IsElementInEnumerable)
                {
                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
                else
                {
                    var exception = new ArgumentOutOfRangeException(exceptionMessage, (Exception)null).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void ContainInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = (IEnumerable)verification.Value;
            var searchForItem = verification.VerificationParameters[0].Value;
            var elementType = verification.VerificationParameters[0].Type;
            foreach (var element in valueAsEnumerable)
            {
                if (EqualUsingDefaultEqualityComparer(elementType, element, searchForItem))
                {
                    return;
                }
            }

            var exceptionMessage = BuildArgumentExceptionMessage(verification, ContainExceptionMessageSuffix, Include.GenericType, genericTypeOverride: elementType);

            var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

            throw exception;
        }

        private static void NotContainInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var valueAsEnumerable = (IEnumerable)verification.Value;
            var searchForItem = verification.VerificationParameters[0].Value;
            var elementType = verification.VerificationParameters[0].Type;
            foreach (var element in valueAsEnumerable)
            {
                if (EqualUsingDefaultEqualityComparer(elementType, element, searchForItem))
                {
                    var exceptionMessage = BuildArgumentExceptionMessage(verification, NotContainExceptionMessageSuffix, Include.GenericType, genericTypeOverride: elementType);

                    var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                    throw exception;
                }
            }
        }

        private static void BeAlphabeticInternal(
            Verification verification)
        {
            BeInCharacterSetInternal(verification, AlphabeticCharactersHashSet, BeAlphabeticExceptionMessageSuffix);
        }

        private static void BeAlphanumericInternal(
            Verification verification)
        {
            BeInCharacterSetInternal(verification, AlphaNumericCharactersHashSet, BeAlphanumericExceptionMessageSuffix);
        }

        private static void BeInCharacterSetInternal(
            Verification verification,
            HashSet<char> allowedCharactersHashSet,
            string exceptionMessageSuffix)
        {
            NotBeNullInternal(verification);

            var otherAllowedCharacters = (IReadOnlyCollection<char>)verification.VerificationParameters[0].Value;

            var stringValue = (string)verification.Value;

            bool shouldThrow;
            if (otherAllowedCharacters == null)
            {
                shouldThrow = stringValue.Any(_ => !allowedCharactersHashSet.Contains(_));
            }
            else
            {
                allowedCharactersHashSet = new HashSet<char>(allowedCharactersHashSet);
                foreach (var otherAllowedCharacter in otherAllowedCharacters)
                {
                    allowedCharactersHashSet.Add(otherAllowedCharacter);
                }

                shouldThrow = stringValue.Any(_ => !allowedCharactersHashSet.Contains(_));
            }

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, exceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeAsciiPrintableInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var treatNewLineAsPrintable = (bool)verification.VerificationParameters[0].Value;

            var stringValue = (string)verification.Value;

            if (treatNewLineAsPrintable)
            {
                stringValue = stringValue.Replace(Environment.NewLine, string.Empty);
            }

            var shouldThrow = stringValue.Any(_ => ((int)_ < 32) || ((int)_ > 126));

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeAsciiPrintableExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void BeMatchedByRegexInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var regex = (Regex)verification.VerificationParameters[0].Value;

            var stringValue = (string)verification.Value;

            var shouldThrow = !regex.IsMatch(stringValue);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, BeMatchedByRegexExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        private static void NotBeMatchedByRegexInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var regex = (Regex)verification.VerificationParameters[0].Value;

            var stringValue = (string)verification.Value;

            var shouldThrow = regex.IsMatch(stringValue);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotBeMatchedByRegexExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [SuppressMessage("Microsoft.Globalization", "CA1307:SpecifyStringComparison", MessageId = "System.String.StartsWith(System.String)", Justification = "User can specify whether to validate with comparisonType or not.")]
        private static void StartWithInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var parameterValue = (string)verification.Value;
            var comparisonValue = (string)verification.VerificationParameters[0].Value;
            var comparisonType = (StringComparison?)verification.VerificationParameters[1].Value;

            var shouldThrow = comparisonType == null
                ? !parameterValue.StartsWith(comparisonValue)
                : !parameterValue.StartsWith(comparisonValue, (StringComparison) comparisonType);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, StartWithExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }

        [SuppressMessage("Microsoft.Globalization", "CA1307:SpecifyStringComparison", MessageId = "System.String.StartsWith(System.String)", Justification = "User can specify whether to validate with comparisonType or not.")]
        private static void NotStartWithInternal(
            Verification verification)
        {
            NotBeNullInternal(verification);

            var parameterValue = (string)verification.Value;
            var comparisonValue = (string)verification.VerificationParameters[0].Value;
            var comparisonType = (StringComparison?)verification.VerificationParameters[1].Value;

            var shouldThrow = comparisonType == null
                ? parameterValue.StartsWith(comparisonValue)
                : parameterValue.StartsWith(comparisonValue, (StringComparison)comparisonType);

            if (shouldThrow)
            {
                var exceptionMessage = BuildArgumentExceptionMessage(verification, NotStartWithExceptionMessageSuffix, Include.FailingValue);

                var exception = new ArgumentException(exceptionMessage).AddData(verification.Data);

                throw exception;
            }
        }
    }
}
