// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TestAssertionVerificationFailedException.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Assertion.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Assertion.Recipes
{
    using System;

    /// <summary>
    /// A verification has failed in a Test assertion.
    /// </summary>
#if !OBeautifulCodeAssertionRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Assertion.Recipes", "See package version number")]
    internal
#else
    public
#endif
        class TestAssertionVerificationFailedException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImproperUseOfAssertionFrameworkException"/> class with a specified error message.
        /// </summary>
        /// <param name="message"></param>
        public TestAssertionVerificationFailedException(string message)
            : base(message)
        {
        }
    }
}
